# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_MDSS_PLL) += mdss-pll-util.o
obj-$(CONFIG_MDSS_PLL) += mdss-pll.o
obj-$(CONFIG_MDSS_PLL) += mdss-dsi-pll-28lpm.o
obj-$(CONFIG_MDSS_PLL) += mdss-dsi-pll-28nm-util.o
